container:
  image: python:3.7
  additional_containers:
    - name: chrome
      image: selenium/standalone-chrome
      port: 4444

pep8_task:
  timeout_in: 10m
  script:
    - pip install git+https://gitlab.com/pycqa/flake8#egg=flake8
    - flake8 --ignore="E501" ./

tests_task:
  timeout_in: 10m
  depends_on:
    - pep8
  script:
    - pip install selenium pyhamcrest -U
    - ./runtests -v

do_release_task:
  timeout_in: 5m
  only_if: $CIRRUS_TAG != ''
  environment:
    PYPI_USER: ENCRYPTED[06791c5ac723b68625a910d321e6fe8977c2f10d214b173836b65791c4fdd0e58030991ba6dea30fa2941ad9526302d2]
    PYPI_PASSWORD: ENCRYPTED[c5412028074e644cbad9d71bed2ca7e6caf72d619332f556e0a410560b2975170f4640834ff739099d7fc7f3311bfd41]
  depends_on:
    - tests
  script:
    - pip install twine
    - ./genpypirc
    - python setup.py sdist
    - twine upload dist/*
